version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: rootrip_database
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - 6379:6379