version: '3.8'
services:
  dev_db:
    image: postgres:latest
    container_name: rootrip_database
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local
    ports:
      - "5433:5433"
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "37001:37001"
    volumes:
      - ../src:/usr/src/app/src
    env_file:
      - ../.env.dev