version: '3.8'
services:
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    container_name: rootrip_database
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testDatabase
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - 6379:6379