# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main','develop']
    pull_request:
        branches: ['main','develop']

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  #  https://stackoverflow.com/questions/61010294/how-to-cache-yarn-packages-in-github-actions
                  cache: 'npm'

            # https://github.com/kiranojhanp/fullstack-typescript-turborepo-starter/blob/main/.github/workflows/api.yaml
            - name: Get npm cache directory path
              id: npm-cache-dir-path
              run: echo "dir=$(npm cache dir)" >> $GITHUB_OUTPUT

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              id: npm-cache
              with:
                  path: ${{ steps.npm-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-


            - name: Install Dependencies
              run: npm install --frozen-lockfile --prefer-offline

            - name: Format Check
              run: npm run format-check
              

            - name: Lint
              run: npm run lint

            - name: Type Check
              run: npm run type-check

            - name: Test
              run: npm run test:ci

            - name: Coveralls
              uses: coverallsapp/github-action@v2
#  https://github.com/actions/typescript-action/blob/main/.github/workflows/codeql-analysis.yml

#  https://github.com/actions/typescript-action/blob/main/.github/workflows/test.yml